### ISSUE TITLE
How to customise form title (e.g. adjust its size)?

### ISSUE THREAD

**Issue by maxalbert** [TriOptima/iommi#277]
First of all, huge thanks for creating `iommi` and making it available!

I'm not sure if this question points to a proper bug, or if it is simply an issue with discoverability / documentation. It's quite likely that I'm missing something obvious, but I can't figure out what it is. Any suggestions or clarification would be highly appreciated.

Let's say I have the following minimal `Page` containing a simple form.
```python
import iommi
from django.db import models


class FooModel(models.Model):
    foo = models.TextField()


class FooForm(iommi.Form):
    class Meta:
        auto__model = FooModel


class MainPage(iommi.Page):
    title = iommi.html.h1("Main Page")
    foo_form = FooForm().create()
```
This is rendered as follows.
<img width="350" alt="Screenshot 2022-05-05 at 01 57 32" src="https://user-images.githubusercontent.com/2692805/166852958-e052f08e-45ec-445c-9699-9945db05cc16.png">

Now, I'd like to change the form title from its default "Create foo title" to something else and also make it a little smaller (in order to visually distinguish it from the page title). It's straightforward to set the form title text by adding `title = "..."` in the form's `Meta`, as follows.
```
class FooForm(iommi.Form):
    class Meta:
        auto__model = FooModel
        title = "Form Title"
```
<img width="350" alt="Screenshot 2022-05-05 at 01 58 34" src="https://user-images.githubusercontent.com/2692805/166853096-ce5f3463-0436-4a96-a4cb-670ba01ce8a9.png">

However, I cannot for the life of me figure out how to customise the size (or other attributes) of the form title.

Here are the different things I tried.

I first used the "Pick" debugging tool to get a hint as to which parameter path to use. When I click on the form title, it shows the following.
<img width="400" alt="Screenshot 2022-05-05 at 02 11 47" src="https://user-images.githubusercontent.com/2692805/166853194-9bf8e552-f3e9-4b23-8532-c6018c6524b6.png">

The last line at the bottom reads `parts__foo_form__h_tag`, so I assumed I could set the `h_tag` attribute in the form's Meta to something else.

The [h_tag docs say](https://docs.iommi.rocks/en/latest/Page.html?highlight=h_tag#refinable-members) that `h_tag` is of type `Union[iommi.fragment.Fragment, str]`, so I thought that I should be able to set it to either a string or an instance of `Fragment`. However, both approaches result in error messages.

Obviously, using a plain string won't help with changing the size, but I tried it anyway to see if it would at least render correctly. However, setting
```python
class FooForm(iommi.Form):
    class Meta:
        auto__model = FooModel
        h_tag = "Form Title"
```
gives
```
AttributeError at /foo/:
'str' object has no attribute 'bind'`.
```
Whereas
```python
class FooForm(iommi.Form):
    class Meta:
        auto__model = FooModel
        h_tag = iommi.Fragment("Form Title", tag="h3")
```
gives
```
AssertionError at /foo/:
refine_done() not invoked on something (h_tag) in the declared namespace of foo_form
```

I also tried to set `title = iommi.html.h3("Form Title")`, but this gives the following error:
```
Traceback (most recent call last):
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/iommi/base.py", line 46, in view_wrapper
    return target.bind(request=request).render_to_response()
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/tri_declarative/dispatch.py", line 10, in dispatch_defaults_wrapper
    return f(*args, **Namespace(defaults, kwargs))
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/iommi/part.py", line 172, in render_to_response
    response = HttpResponse(render_root(part=self, **kwargs))
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/tri_declarative/dispatch.py", line 10, in dispatch_defaults_wrapper
    return f(*args, **Namespace(defaults, kwargs))
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/iommi/part.py", line 212, in render_root
    content = part.__html__(**render)
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/tri_declarative/dispatch.py", line 10, in dispatch_defaults_wrapper
    return f(*args, **Namespace(defaults, kwargs))
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/iommi/page.py", line 112, in __html__
    for name, part in items(self.parts)
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/iommi/base.py", line 67, in items
    return type(container).items(container)
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/iommi/member.py", line 233, in items
    _force_bind_all(self)
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/iommi/member.py", line 277, in _force_bind_all
    _force_bind(member_binder, name)
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/iommi/member.py", line 258, in _force_bind
    bound_member = _declared_members[name].bind(parent=_parent)
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/iommi/part.py", line 109, in bind
    result = super(Part, self).bind(parent=parent, request=request)
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/iommi/traversable.py", line 175, in bind
    result.on_bind()
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/iommi/form.py", line 1535, in on_bind
    build_and_bind_h_tag(self)
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/iommi/fragment.py", line 243, in build_and_bind_h_tag
    p.h_tag = p.h_tag(_name='h_tag', children__text=capitalize(evaluate_strict(p.title, **p.iommi_evaluate_parameters()))).bind(parent=p)
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/iommi/base.py", line 58, in capitalize
    return s[0].upper() + s[1:] if s else s

Exception Type: TypeError at /foo/
Exception Value: 'Fragment' object is not subscriptable
```

Finally, I tried to set the style/class attribute of the title element by adding one of the following to the form's `Meta`.
```
title__attrs__style = "font-size:smaller;"
title__attrs__style = {"font-size": "smaller"}
title__attrs__class = "foo-class"
title__attrs__class = {"foo-clas": True}
```
However, each of these results in yet another error:
```
Traceback (most recent call last):
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/iommi/base.py", line 46, in view_wrapper
    return target.bind(request=request).render_to_response()
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/tri_declarative/dispatch.py", line 10, in dispatch_defaults_wrapper
    return f(*args, **Namespace(defaults, kwargs))
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/iommi/part.py", line 172, in render_to_response
    response = HttpResponse(render_root(part=self, **kwargs))
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/tri_declarative/dispatch.py", line 10, in dispatch_defaults_wrapper
    return f(*args, **Namespace(defaults, kwargs))
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/iommi/part.py", line 212, in render_root
    content = part.__html__(**render)
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/tri_declarative/dispatch.py", line 10, in dispatch_defaults_wrapper
    return f(*args, **Namespace(defaults, kwargs))
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/iommi/page.py", line 112, in __html__
    for name, part in items(self.parts)
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/iommi/base.py", line 71, in items
    return type(container).items(container)
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/iommi/member.py", line 233, in items
    _force_bind_all(self)
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/iommi/member.py", line 277, in _force_bind_all
    _force_bind(member_binder, name)
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/iommi/member.py", line 258, in _force_bind
    bound_member = _declared_members[name].bind(parent=_parent)
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/iommi/part.py", line 109, in bind
    result = super(Part, self).bind(parent=parent, request=request)
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/iommi/traversable.py", line 175, in bind
    result.on_bind()
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/iommi/form.py", line 1535, in on_bind
    build_and_bind_h_tag(self)
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/iommi/fragment.py", line 243, in build_and_bind_h_tag
    p.h_tag = p.h_tag(_name='h_tag', children__text=capitalize(evaluate_strict(p.title, **p.iommi_evaluate_parameters()))).bind(parent=p)
  File "/Users/maxalbert/code/iommi_example/venv/lib/python3.10/site-packages/iommi/base.py", line 59, in capitalize
    return s[0].upper() + s[1:] if s else s

Exception Type: KeyError at /foo/
Exception Value: 0
```

What am I missing? Many thanks for any suggestions!

**Comment by boxed** [comment]
First of all it's very cool to see the amount of research you did and using the pick tool!

The answer:

`h_tag__attrs__class__foo=True` or something. It's a Fragment as you found out so can be refined with attrs like most things in iommi. 

Hope this is clear!

**Comment by boxed** [comment]
Absolutely. I not only think it's possible, this is the type of thing we think is *mandatory* :P

Not sure it's straightforward. But writing a test should be fairly simple I think.

**Comment by jlubcke** [comment]
I think it is a bug that it fails to send your own `Fragment` to replace the default. That should be fixed I think.

**Comment by jlubcke** [comment]
Some parts of the title/header setting is overly complicated maybe...
